const knowledgeGraph = {
    nodes: [
        { id: 'react', label: 'React', group: 'frontend', mastery: 72, description: 'A JavaScript library for building user interfaces using components.' },
        { id: 'hooks', label: 'React Hooks', group: 'frontend', mastery: 65, description: 'Functions that let you use state and lifecycle features in functional components.' },
        { id: 'jsx', label: 'JSX', group: 'frontend', mastery: 85, description: 'A syntax extension for JavaScript that looks similar to XML/HTML.' },
        { id: 'state', label: 'State Management', group: 'frontend', mastery: 55, description: 'Techniques for managing and sharing state across components.' },
        { id: 'redux', label: 'Redux', group: 'frontend', mastery: 40, description: 'A predictable state container for JavaScript apps.' },
        { id: 'context', label: 'Context API', group: 'frontend', mastery: 60, description: 'Reacts built-in way to pass data through the component tree.' },
        { id: 'node', label: 'Node.js', group: 'backend', mastery: 68, description: 'A JavaScript runtime built on Chrome V8 engine for server-side code.' },
        { id: 'express', label: 'Express.js', group: 'backend', mastery: 70, description: 'A minimal and flexible Node.js web application framework.' },
        { id: 'rest', label: 'REST APIs', group: 'backend', mastery: 75, description: 'Architectural style for designing networked applications using HTTP.' },
        { id: 'graphql', label: 'GraphQL', group: 'backend', mastery: 35, description: 'A query language for APIs and a runtime for executing those queries.' },
        { id: 'sql', label: 'SQL', group: 'database', mastery: 60, description: 'Structured Query Language for managing relational databases.' },
        { id: 'postgres', label: 'PostgreSQL', group: 'database', mastery: 50, description: 'A powerful open-source relational database system.' },
        { id: 'mongodb', label: 'MongoDB', group: 'database', mastery: 45, description: 'A document-oriented NoSQL database for high volume data storage.' },
        { id: 'redis', label: 'Redis', group: 'database', mastery: 30, description: 'An in-memory data structure store used as database, cache, and broker.' },
        { id: 'docker', label: 'Docker', group: 'devops', mastery: 55, description: 'A platform to develop, ship, and run applications in containers.' },
        { id: 'k8s', label: 'Kubernetes', group: 'devops', mastery: 25, description: 'An open-source system for automating deployment and scaling of containerized apps.' },
        { id: 'ci_cd', label: 'CI/CD', group: 'devops', mastery: 50, description: 'Continuous Integration and Delivery practices for automated software releases.' },
        { id: 'git', label: 'Git', group: 'devops', mastery: 80, description: 'A distributed version control system for tracking changes in source code.' },
        { id: 'typescript', label: 'TypeScript', group: 'frontend', mastery: 58, description: 'A typed superset of JavaScript that compiles to plain JavaScript.' },
        { id: 'testing', label: 'Testing', group: 'quality', mastery: 45, description: 'Practices and tools for verifying software correctness.' },
        { id: 'jest', label: 'Jest', group: 'quality', mastery: 50, description: 'A delightful JavaScript testing framework with a focus on simplicity.' },
        { id: 'webpack', label: 'Webpack', group: 'frontend', mastery: 42, description: 'A static module bundler for modern JavaScript applications.' },
        { id: 'vite_tool', label: 'Vite', group: 'frontend', mastery: 70, description: 'A next-generation frontend tooling with instant server start.' },
        { id: 'auth', label: 'Authentication', group: 'security', mastery: 55, description: 'Verifying user identity using tokens, sessions, or OAuth protocols.' },
        { id: 'jwt', label: 'JWT', group: 'security', mastery: 48, description: 'JSON Web Tokens for securely transmitting information between parties.' },
        { id: 'oauth', label: 'OAuth 2.0', group: 'security', mastery: 35, description: 'An authorization framework enabling third-party access to resources.' },
        { id: 'css', label: 'CSS', group: 'frontend', mastery: 78, description: 'Cascading Style Sheets for styling and layout of web pages.' },
        { id: 'nextjs', label: 'Next.js', group: 'frontend', mastery: 52, description: 'A React framework for production with SSR and static site generation.' },
        { id: 'python', label: 'Python', group: 'backend', mastery: 62, description: 'A versatile programming language used for web, AI, data science, and more.' },
        { id: 'fastapi', label: 'FastAPI', group: 'backend', mastery: 38, description: 'A modern fast Python web framework for building APIs.' },
    ],
    links: [
        { source: 'react', target: 'hooks' },
        { source: 'react', target: 'jsx' },
        { source: 'react', target: 'state' },
        { source: 'react', target: 'context' },
        { source: 'react', target: 'css' },
        { source: 'react', target: 'typescript' },
        { source: 'react', target: 'nextjs' },
        { source: 'state', target: 'redux' },
        { source: 'state', target: 'context' },
        { source: 'node', target: 'express' },
        { source: 'node', target: 'rest' },
        { source: 'express', target: 'rest' },
        { source: 'rest', target: 'graphql' },
        { source: 'sql', target: 'postgres' },
        { source: 'mongodb', target: 'node' },
        { source: 'redis', target: 'node' },
        { source: 'docker', target: 'k8s' },
        { source: 'docker', target: 'ci_cd' },
        { source: 'git', target: 'ci_cd' },
        { source: 'testing', target: 'jest' },
        { source: 'react', target: 'testing' },
        { source: 'react', target: 'webpack' },
        { source: 'react', target: 'vite_tool' },
        { source: 'auth', target: 'jwt' },
        { source: 'auth', target: 'oauth' },
        { source: 'express', target: 'auth' },
        { source: 'nextjs', target: 'react' },
        { source: 'python', target: 'fastapi' },
        { source: 'fastapi', target: 'rest' },
        { source: 'postgres', target: 'node' },
    ]
};

const groupColors = {
    frontend: '#6366f1',
    backend: '#10b981',
    database: '#f59e0b',
    devops: '#ef4444',
    quality: '#8b5cf6',
    security: '#ec4899',
};

export { knowledgeGraph, groupColors };
